language: go
go:
  - "1.8.x"
dist: trusty
sudo: true
group: edge

env:
  - CHANGE_MINIKUBE_NONE_USER=true

jobs:
  include:
    - stage: "OpenShift and Kubernetes CI"
      script:
        - ./fake-openshift.sh
    -
      script:
        - ./setup-minikube.sh
        - ./setup-broker.sh
